<a href="https://colab.research.google.com/github/naathycc/Estudos-para-projeto-trainee-de-dados/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3,4,5,6])
print(array1)
print(type(array1))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
array2 = np.array([[1,2,3], [4,5,6]])
print(array2)

[[1 2 3]
 [4 5 6]]


In [ ]:
array3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(array3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
array4 = np.array([1,2,3,4], ndmin = 7)
print(array4)

[[[[[[[1 2 3 4]]]]]]]


In [ ]:
print(array4.ndim)

7


In [ ]:
## Criar um array de 0 a 20
array5 = np.arange(21)
print(array5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
array6 = np.arange(2,11,2)
print(array6)

[ 2  4  6  8 10]


In [ ]:
array7 = np.linspace(0,100,5)
print(array7)

[  0.  25.  50.  75. 100.]


In [ ]:
# array_zeros = np.zeros(5)
# print(array_zeros)

matriz_zeros = np.zeros((3, 4))
print(matriz_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
array8 = np.array([1,2,3,4,5])
print(array8.dtype)

int64


In [ ]:
array9 = np.array([20,30,40])
print(array9.shape)

(3,)


In [ ]:
array10 = np.array([[10, 20, 30], [40, 50, 60]])
print(array10)
print(array10.shape)


[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
print(array10.size)

6


In [ ]:
print(array10.ndim)

2


In [ ]:
array_float = np.array([1.2, 3.8, 4.7])
print(array_float.dtype)

array_cast = array_float.astype(int)
print(array_cast)
print(array_cast.dtype)

float64
[1 3 4]
int64


In [ ]:
array11 = np.arange(1,5)
array12 = np.arange(5,9)

print("A soma deu: ", array11 + array12)
print("A subtração deu: ", array11 - array12)
print("A divisão deu: ", array12 / array11)
print("A multiplicação deu: ", array11 * array12)
print("A potencia deu: ", array11 ** 4)



A soma deu:  [ 6  8 10 12]
A subtração deu:  [-4 -4 -4 -4]
A divisão deu:  [5.         3.         2.33333333 2.        ]
A multiplicação deu:  [ 5 12 21 32]
A potencia deu:  [  1  16  81 256]


In [ ]:
array13 = np.array([10,20,30,40,50])
numero = 5

soma = array13 + numero
print(soma)

[15 25 35 45 55]


In [ ]:
array14 = np.array([1,2,3,4,5])
print("O resultado das soma dos elementos é: ",array14.sum())


array15 = np.array([[1,2,3,4], [5,6,7,8]])
print("O resultado das soma dos elementos da matriz é: ",array15.sum())
print("A soma por coluna é: ",array15.sum(axis=0))
print("A soma por linha é: ",array15.sum(axis=1))
print("A média do nosso array é: ",array14.mean())
print("O desvio padrão nosso array é: ",array14.std())
print("O menor elemento do array é: ",array14.min())
print("O maior elemento do array é: ",array14.max())
print("O indice do maior elemento é: ",array14.argmax())

O resultado das soma dos elementos é:  15
O resultado das soma dos elementos da matriz é:  36
A soma por coluna é:  [ 6  8 10 12]
A soma por linha é:  [10 26]
A média do nosso array é:  3.0
O desvio padrão nosso array é:  1.4142135623730951
O menor elemento do array é:  1
O maior elemento do array é:  5
O indice do maior elemento é:  4


In [ ]:
array15 = np.array([1,2,3,4,5])
array16 = np.array([10,11,12,4,5])
print("Os elementos dos arrays são iguais? ", array15 == array16)
print("Os elementos dos array 16 são maiores ou iguais do que do array 15? ", array15 <= array16)


Os elementos dos arrays são iguais?  [False False False  True  True]
Os elementos dos array 16 são maiores ou iguais do que do array 15?  [ True  True  True  True  True]
Os elementos dos array 15 são menores ou iguais do que do array 16?  [False False False  True  True]


In [ ]:
array17 = np.array([False, True, True])
array18 = np.array([False, False, False])
print(array17)
print(array18)
print("array17 AND array18: ",array17 & array18)
print("array17 OR array18: ",array17 | array18)
print("NOT array17: ", ~array17)
print("NOT array18: ", ~array18)

[False  True  True]
[False False False]
array17 AND array18:  [False False False]
array17 OR array18:  [False  True  True]
NOT array17:  [ True False False]
NOT array18:  [ True  True  True]


In [ ]:
array19 = np.arange(10, 60, 10)
print(array19)

print("Primeiro elemento do array: ",array19[0])
print("Último elemento do array: ",array19[-1])

array20 = np.array([[1,2,3], [4,5,6] ,[7,8,9]])
print(array20)
print("Elemento da 1º linha e 1º coluna da matriz: ",array20[0][0])
print("Elemento da 3º linha e 1º coluna da matriz: ",array20[-1][0])

[10 20 30 40 50]
Primeiro elemento do array:  10
Último elemento do array:  50
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento da 1º linha e 1º coluna da matriz:  1
Elemento da 3º linha e 1º coluna da matriz:  7


In [ ]:
array21 = np.arange(10)
print(array21)
print("Fatiamento: ", array21[1:10:2])
print("Fatiamento: ", array21[:10:2])
print("Fatiamento: ", array21[::2])
print("Fatiamento: ", array21[5::])





[0 1 2 3 4 5 6 7 8 9]
Fatiamento:  [1 3 5 7 9]
Fatiamento:  [0 2 4 6 8]
Fatiamento:  [0 2 4 6 8]
Fatiamento:  [5 6 7 8 9]


In [ ]:
array23 = np.arange(0, 11)
print(array23)
condicao1 = array23 > 2
condicao2 = array23 % 2 == 0

elementos = array23[condicao1 & condicao2]
print("Elementos maiores que 2 e que são pares: ",elementos)

array24 = np.array([[10,20,30],
                    [40,50,60],
                    [70,80,90]])
print(array24)
condicao3 = array24 > 50
elementos1 = array24[condicao3]
print("Elementos maiores que 50",elementos1)

[ 0  1  2  3  4  5  6  7  8  9 10]
Elementos maiores que 2 e que são pares:  [ 4  6  8 10]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Elementos maiores que 50 [60 70 80 90]


In [ ]:
array25 = np.arange(12)
print(array25)

matriz_4x3 = array25.reshape(4,3)
print(matriz_4x3)

matriz_3x4 = array25.reshape(3,4)
print(matriz_3x4)

matriz_2 = array25.reshape(2, -1)
print(matriz_2)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [ ]:
array26 = np.array([1,2,3,4])
print(array26)
array_coluna = array26[:, np.newaxis]
print(array_coluna)
array_linha = array26[np.newaxis, :]
print(array_linha)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [ ]:
array27 = np.array([[1,2], [3,4]])
print(array27)
print(array27.shape)
print("Transpondo a matriz original: ",array27.T)
array_achatado = array27.flatten()
print("Array achatado: ",array_achatado)

[[1 2]
 [3 4]]
(2, 2)
Transpondo a matriz original:  [[1 3]
 [2 4]]
Array achatado:  [1 2 3 4]


In [ ]:
array28 = np.array([1,2,3])
array29 = np.array([4,5,6])
print("Empilhamento vertical: ", np.vstack((array28, array29)))
print("Empilhamento horizontal: ", np.hstack((array28, array29)))
print("Concatenar: ", np.concatenate((array28, array29), axis=0))

Empilhamento vertical:  [[1 2 3]
 [4 5 6]]
Empilhamento horizontal:  [1 2 3 4 5 6]
Concatenar:  [1 2 3 4 5 6]


In [66]:
# ==========================================
# EXERCÍCIO 1 - ATRIBUTOS DE ARRAYS
# ==========================================

# Crie o array:
# arr = np.array([[1,2,3],[4,5,6]])

# Mostre:
# - Número de dimensões
# - Shape
# - Quantidade total de elementos
# - Tipo dos elementos

arr = np.array([[1,2,3],[4,5,6]])
print("Exercício 1: ")
print("Número de dimensões: ",arr.ndim)
print("Shape: ",arr.shape)
print("Quantidade total de elementos: ",arr.size)
print("Tipos de elementos: ",arr.dtype)

# ==========================================
# EXERCÍCIO 2 - OPERAÇÕES COM ARRAYS
# ==========================================

# Crie os arrays:
# a = np.array([1,2,3])
# b = np.array([4,5,6])

# Mostre:
# - Soma
# - Subtração
# - Multiplicação
# - Divisão

print("Exercício 2: ")
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Soma: ",a+b)
print("Subtração: ",a-b)
print("Multiplicação: ",a*b)
print("Divisão: ",b/a)
# ==========================================
# EXERCÍCIO 3 - FUNÇÕES DE AGREGAÇÃO
# ==========================================

# Crie o array:
# arr1 = np.array([10,20,30,40,50])

# Mostre:
# - Soma total
# - Média
# - Maior valor
# - Menor valor

arr1 = np.array([10,20,30,40,50])
print("Exercício 3")
print("Soma total: ",arr1.sum())
print("Média: ",arr1.mean())
print("Maior valor: ",arr1.max())
print("Menor valor: ",arr1.min())

# ==========================================
# EXERCÍCIO 4 - OPERAÇÕES LÓGICAS
# ==========================================

# Crie o array:
# arr = np.array([5,10,15,20,25])

# Mostre:
# - Elementos maiores que 15
# - Elementos iguais a 10

arr2 = np.array([5,10,15,20,25])
print("Exercício 4: ")
elementos_maiores = arr2 > 15
elementos_iguais = arr2 == 10
print("Elementos maiores que 15: ", arr2[elementos_maiores])
print("Elementos iguais a 10: ", arr2[elementos_iguais])

# ==========================================
# EXERCÍCIO 5 - INDEXAÇÃO E FATIAMENTO
# ==========================================

# Crie o array:
# arr = np.array([10,20,30,40,50,60,70,80])

# Mostre:
# - Primeiro elemento
# - Último elemento
# - Elementos da posição 2 até 5
# - Elementos de 2 em 2

arr3 = np.array([10,20,30,40,50,60,70,80])
print("Exercício 5: ")
print("Primeiro elemento: ",arr3[0])
print("Último elemento: ",arr3[-1])
print("Elementos da posição 2 até 5: ",arr3[2:6])
print("Elementos de 2 em 2: ",arr3[::2])


# ==========================================
# EXERCÍCIO 6 - MANIPULAÇÃO DE FORMAS
# ==========================================

# Crie o array:
# arr = np.array([1,2,3,4,5,6])

# Transforme-o em uma matriz 3x2:
#
# [[1 2]
#  [3 4]
#  [5 6]]

arr4 = np.array([1,2,3,4,5,6])
print("Exercício 6: ")
print("Transformação em uma matriz 3x2: ",arr4.reshape(3,2))

# ==========================================
# EXERCÍCIO 7 - MATRIZ TRANSPOSTA
# ==========================================

# Crie a matriz:
#
# [[1,2,3],
#  [4,5,6]]
#
# Mostre a matriz transposta.

print("Exercício 7: ")
matriz12 = np.array([[1,2,3],
 [4,5,6]])
print(matriz12)
print("Matriz transposta: ", matriz12.T)


# ==========================================
# EXERCÍCIO 8 - DIVISÃO DE ARRAYS
# ==========================================

# Crie o array:
# arr = np.array([1,2,3,4,5,6,7,8])

# Divida o array em 4 partes iguais.

arr5 = np.array([1,2,3,4,5,6,7,8])
print("Exercício 8: ")
print("Dividindo o array em 4 partes: ",np.split(arr5, 4))

Exercício 1: 
Número de dimensões:  2
Shape:  (2, 3)
Quantidade total de elementos:  6
Tipos de elementos:  int64
Exercício 2: 
Soma:  [5 7 9]
Subtração:  [-3 -3 -3]
Multiplicação:  [ 4 10 18]
Divisão:  [4.  2.5 2. ]
Exercício 3
Soma total:  150
Média:  30.0
Maior valor:  50
Menor valor:  10
Exercício 4: 
Elementos maiores que 15:  [20 25]
Elementos iguais a 10:  [10]
Exercício 5: 
Primeiro elemento:  10
Último elemento:  80
Elementos da posição 2 até 5:  [30 40 50 60]
Elementos de 2 em 2:  [10 30 50 70]
Exercício 6: 
Transformação em uma matriz 3x2:  [[1 2]
 [3 4]
 [5 6]]
Exercício 7: 
[[1 2 3]
 [4 5 6]]
Matriz transposta:  [[1 4]
 [2 5]
 [3 6]]
Exercício 8: 
Dividindo o array em 4 partes:  [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
